name: Daily Python Script


on:
  schedule:
    - cron: "*/10 * * * *"   # draait elke 10 minuten
  workflow_dispatch:          # handmatig starten

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python script.py    # <-- pas dit aan naar jouw bestandsnaam
