name: Daily Python Script


on:
  schedule:
    - cron: "*/10 * * * *"   # draait elke 10 minuten
  workflow_dispatch:          # handmatig starten

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python script.py 
